sudo : required
services :
  - docker

before_install :
  # - docker build -t ogiku85/docker-react -f Dockerfile.dev .
  - docker build -t ogiku85/docker-react -f Dockerfile .

# scripts :
#   - docker run ogiku85/docker-react npm run test -- --coverage
# added language to prevent trvais ci failure
language: generic
deploy :
  provider : elasticbeanstalk
  region : "us-east-2"
  app : "docker-react"
  env : "DockerReact-env"
  bucket_name : "elasticbeanstalk-us-east-2-292811935698"
  bucket_path : "docker-react"
  on :
    branch : master 
  access_key_id : $AWS_ACCESS_KEY
  secret_access_key : 
    secure : "$AWS_SECRET_KEY"
