sudo : required
services :
  - docker

before_install :
  - docker build -t ogiku85/docker-react -f Dockerfile.dev .git add
scripts :
  - docker run ogiku85/docker-react npm run test -- --coveragegit add